### ISSUE TITLE
Bug UI Material3

### ISSUE THREAD

**Issue by WahyuDwe** [zulfahmi93/month-year-picker#28]
some text months are cropped i.e. apr, aug, dec

**Comment by alfonsotesone** [comment]
Same problem here! :)

**Comment by bahaAbualkibash** [comment]
Same here

**Comment by julvikramsupandi** [comment]
Same problem

**Comment by bahaAbualkibash** [comment]
for anyone that still facing this issue use this forked version instead: https://github.com/dimas-nur/month-year-picker like this: 
`dependencies:
  library_name:
   git: https://github.com/username/library_name
`

**Comment by WahyuDwe** [comment]
where should i put that?

**Comment by WahyuDwe** [comment]
Thankyou @bahaAbualkibash it solved i will close this issue :)
